server {
    listen 82;
    server_name localhost;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location /mis-negocios/ {
        try_files $uri $uri/ /mis-negocios/index.html;
    }

    # Redirecciona la raíz a la subruta por comodidad en pruebas
    location / {
        return 301 /mis-negocios/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
