name: CI/CD sa-sacom-mybusiness-ui Deploy (Docker Multi-Environment)

on:
  push:
    branches:
      - main
      - 'hotfix*'
      - 'release*'
  workflow_dispatch:

jobs:
  trigger-deploy:
    name: Call Centralized Deploy Pipeline
    uses: adsa-sistemas/DevOps-ADSA/.github/workflows/deploy-sa-sacom-mybusiness-ui.yml@main
    secrets: inherit
    with:
      environment: ${{ (github.ref_name == 'main' && 'prod') || (startsWith(github.ref_name, 'release') && 'release') || (startsWith(github.ref_name, 'hotfix') && 'hotfix') }}
      ref_name: ${{ github.ref_name }}
